"""The sdist ships the package, its licence and its ADRs — nothing else.

`pyproject.toml`'s `[tool.hatch.build.targets.sdist]` is an explicit
include/exclude pair specifically so a git worktree's `reference/` symlink (a
1.2 GB pinned clone of the upstream Rust) and the fixture corpus, the
`.chat_history/`, the `.claude/` agent scratch and `todo/` never reach a
publication. hatchling also force-includes files outside that config
entirely — see `hatch_build.py`'s docstring for the `.gitignore` and
`hatch_build.py` cases it strips back out. This test builds the sdist for
real (not a config assertion) and checks the archive that comes out, so a
regression in either the config or the build hook is caught here rather than
at upload.

Slow because it shells out to `uv build`, which resolves and (re)builds; the
whole file is marked `slow` rather than guessing at a threshold per machine.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import tarfile
from dataclasses import dataclass
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent

pytestmark = pytest.mark.slow

ALLOWED_TOP_LEVEL = {
    "src",
    "docs",
    "README.md",
    "LICENSE",
    "NOTICE",
    "pyproject.toml",
    "PKG-INFO",  # generated by hatchling itself; not something we control
}

FORBIDDEN = re.compile(r"reference|\.pst$|private|chat_history|worktrees", re.IGNORECASE)


@dataclass(frozen=True)
class BuiltSdist:
    path: Path
    members: list[str]


@pytest.fixture(scope="module")
def sdist(tmp_path_factory: pytest.TempPathFactory) -> BuiltSdist:
    if shutil.which("uv") is None:
        pytest.skip("uv is not on PATH")

    out_dir = tmp_path_factory.mktemp("sdist")
    result = subprocess.run(
        ["uv", "build", "--sdist", "--out-dir", str(out_dir)],
        cwd=REPO,
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    assert result.returncode == 0, f"uv build --sdist failed:\n{result.stdout}\n{result.stderr}"

    tarballs = list(out_dir.glob("*.tar.gz"))
    assert len(tarballs) == 1, f"expected exactly one sdist, found {tarballs}"

    with tarfile.open(tarballs[0]) as tar:
        return BuiltSdist(path=tarballs[0], members=tar.getnames())


@pytest.fixture(scope="module")
def sdist_members(sdist: BuiltSdist) -> list[str]:
    return sdist.members


def _top_level(member: str) -> str:
    # Each member is "<name>-<version>/<rest...>"; the allow-list is checked
    # one path segment below the version-stamped root directory.
    parts = member.split("/", 2)
    return parts[1] if len(parts) > 1 else parts[0]


def test_sdist_top_level_is_allow_listed(sdist_members: list[str]) -> None:
    top_level = {_top_level(m) for m in sdist_members}
    assert top_level <= ALLOWED_TOP_LEVEL, f"unexpected top-level entries: {top_level - ALLOWED_TOP_LEVEL}"


def test_sdist_has_no_forbidden_content(sdist_members: list[str]) -> None:
    hits = [m for m in sdist_members if FORBIDDEN.search(m)]
    assert not hits, f"forbidden paths in sdist: {hits}"


def test_sdist_contains_the_package(sdist_members: list[str]) -> None:
    assert any(m.endswith("src/pypstreader/pypstreader.py") for m in sdist_members)
    assert any(m.endswith("docs/adr/0003-unicode-only.md") for m in sdist_members)


def test_sdist_is_small(sdist: BuiltSdist) -> None:
    size = sdist.path.stat().st_size
    assert size < 1_000_000, f"sdist is {size} bytes, expected under 1 MB"
