"""What the synthetic fixture SAYS, asserted against the mail we wrote.

Every vendor store in the corpus proves that structures parse. None can prove
that a message says what it should, because nobody here wrote the mail.
`tests/fixtures/public/synth-basics.pst` is different: it was generated by
`scripts/make_fixture.py` from `tests/fixtures/synthetic/basics/`, seven
`.eml` files we authored with example.test addresses and invented names. The
sources are the expectation; the store is the thing under test.

Three tiers, in order of how much of the port they need:

1. **Goldens** (no pypst code): folder names and message counts from the
   oracle's `read_ipm_subtree` / `read_root_folder`, the store's display name
   and derived record key from `read_store_props`, and the admission fact
   itself — the oracle exits 0 on every example that matters.
2. **Bytes** (no pypst code): EMLtoPST writes an UNENCRYPTED store
   (`bCryptMethod` = 0, asserted first), so a PT_UNICODE value sits in the
   file as plain UTF-16LE and an attachment as its raw bytes. Searching the
   file for the authored subject is crude, but it is a real content assertion
   available today, and it pins the generator: if the tool ever encodes,
   compresses or mangles a value, this tier says so before P09 exists.
3. **The reader** (skips until P07–P09 land): the same expectations read back
   through `pypst.Store` / `Folder` / `Message` / `Attachment`, written to
   `docs/INTERFACES.md` § messaging so they go live without edits.

Plus the policy tests that keep future synthetic sources honest, and the
regeneration check that keeps the committed store honest.
"""

from __future__ import annotations

import email
import email.policy
import hashlib
import itertools
import re
import struct
import subprocess
import sys
import zlib
from dataclasses import dataclass, field
from pathlib import Path

import pytest

from tests.conftest import PUBLIC, REPO

SYNTHETIC = REPO / "tests" / "fixtures" / "synthetic"
SOURCES = SYNTHETIC / "basics"
STORE = PUBLIC / "synth-basics.pst"
TOOL = REPO / "reference" / "EMLtoPST"
MAKE_FIXTURE = REPO / "scripts" / "make_fixture.py"

ALLOWED_DOMAINS = ("example.test", "example.com")

# scripts/make_fixture.py: the store layout it writes around the sources.
IPM_SUBTREE_NAME = "Top of Personal Folders"
FINDER_NAME = "Search Root"
WASTEBASKET_NAME = "Deleted Items"

# The six examples a synthetic store must pass to enter the corpus
# (todo/T06-testing.md § P20-SYNTH), and the one it is documented to fail.
ADMISSION_EXAMPLES = [
    "read_header",
    "read_btrees",
    "read_store_props",
    "read_named_props",
    "read_root_folder",
    "read_ipm_subtree",
]

NDB_CRYPT_NONE = 0
CRYPT_METHOD_OFFSET = 0x201  # [MS-PST] 2.2.2.6 HEADER.bCryptMethod (Unicode)

# MAPI recipient types ([MS-OXPROPS] PidTagRecipientType).
MAPI_TO, MAPI_CC, MAPI_BCC = 1, 2, 3


# --- the expectation: parsed from the sources, independently of the tool ------


@dataclass
class ExpectedMessage:
    folder: str
    source: Path
    subject: str  # "" when the header is absent
    sender_name: str
    sender_email: str
    recipients: list[tuple[int, str, str]] = field(default_factory=list)  # (type, name, email)
    body_text: str | None = None
    body_html: str | None = None
    attachments: list[tuple[str, str, bytes]] = field(default_factory=list)  # (filename, mime, payload)


def _addresses(msg: email.message.EmailMessage, header: str) -> list[tuple[str, str]]:
    value = msg[header]
    if value is None:
        return []
    return [(a.display_name or a.addr_spec, a.addr_spec) for a in value.addresses]


def expected_messages(root: Path = SOURCES) -> list[ExpectedMessage]:
    out: list[ExpectedMessage] = []
    for path in sorted(root.rglob("*.eml")):
        msg = email.message_from_bytes(path.read_bytes(), policy=email.policy.default)
        sender = _addresses(msg, "From")[0]
        expected = ExpectedMessage(
            folder=path.parent.name,
            source=path,
            subject=str(msg["Subject"]) if msg["Subject"] is not None else "",
            sender_name=sender[0],
            sender_email=sender[1],
        )
        for header, kind in (("To", MAPI_TO), ("Cc", MAPI_CC), ("Bcc", MAPI_BCC)):
            expected.recipients += [(kind, name, addr) for name, addr in _addresses(msg, header)]
        plain = msg.get_body(preferencelist=("plain",))
        html = msg.get_body(preferencelist=("html",))
        expected.body_text = plain.get_content() if plain is not None else None
        expected.body_html = html.get_content() if html is not None else None
        for part in msg.iter_attachments():
            expected.attachments.append(
                (part.get_filename(), part.get_content_type(), part.get_payload(decode=True))
            )
        out.append(expected)
    return out


def expected_folder_counts(root: Path = SOURCES) -> dict[str, int]:
    counts: dict[str, int] = {}
    for m in expected_messages(root):
        counts[m.folder] = counts.get(m.folder, 0) + 1
    return counts


def _text_forms(text: str) -> tuple[str, ...]:
    """The MIME layer, not the store, decides line endings: a 7-bit part comes
    back LF-normalised, a base64 part verbatim, and the part before a boundary
    loses its final newline. Accept any of those spellings of the same text."""
    lf = text.replace("\r\n", "\n")
    stripped = lf.rstrip("\n")
    return (lf, lf.replace("\n", "\r\n"), stripped, stripped.replace("\n", "\r\n"))


def _utf16_present(data: bytes, text: str) -> bool:
    return any(form.encode("utf-16-le") in data for form in _text_forms(text))


def make_swatch_png() -> bytes:
    """The PNG attached to 04-attachments.eml, regenerated from the stdlib
    recipe it was made with. No binary blob came from anywhere else."""

    def chunk(kind: bytes, payload: bytes) -> bytes:
        crc = zlib.crc32(kind + payload) & 0xFFFFFFFF
        return struct.pack(">I", len(payload)) + kind + payload + struct.pack(">I", crc)

    width = height = 8
    rows = b"".join(
        b"\x00" + b"".join(bytes((x * 32, y * 32, 128)) for x in range(width)) for y in range(height)
    )
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(rows, 9))
        + chunk(b"IEND", b"")
    )


# --- golden parsing: the table dumps, minimally ---------------------------------

_ROW = re.compile(r"^Row: 0x([0-9A-F]+)$", re.MULTILINE)
_COLUMN = re.compile(
    r"^ Column: Property ID: 0x([0-9A-F]{4}), Type: \w+\n(?:  Record: .*\n)?  Value: (.*)$",
    re.MULTILINE,
)
_UNICODE = re.compile(r'^Unicode\(UnicodeValue \{ "(.*)" \}\)$')
_INT32 = re.compile(r"^Integer32\((-?\d+)\)$")
_BOOL = re.compile(r"^Boolean\((true|false)\)$")


def table_rows(text: str) -> list[dict[int, str]]:
    """`read_root_folder` / `read_ipm_subtree` output → one {prop_id: value} per row."""
    starts = [m.start() for m in _ROW.finditer(text)] + [len(text)]
    rows = []
    for begin, end in itertools.pairwise(starts):
        rows.append({int(pid, 16): value for pid, value in _COLUMN.findall(text[begin:end])})
    return rows


def unicode_value(value: str) -> str:
    match = _UNICODE.match(value)
    assert match, f"not a Unicode column value: {value!r}"
    return match.group(1)


def int_value(value: str) -> int:
    match = _INT32.match(value)
    assert match, f"not an Integer32 column value: {value!r}"
    return int(match.group(1))


def bool_value(value: str) -> bool:
    match = _BOOL.match(value)
    assert match, f"not a Boolean column value: {value!r}"
    return match.group(1) == "true"


def folder_table(text: str) -> dict[str, dict[str, object]]:
    """display name → {count, unread, has_subfolders} from a hierarchy-table dump."""
    out = {}
    for row in table_rows(text):
        out[unicode_value(row[0x3001])] = {
            "count": int_value(row[0x3602]),
            "unread": int_value(row[0x3603]),
            "has_subfolders": bool_value(row[0x360A]),
        }
    return out


# --- 0. the sources obey the authoring rules -------------------------------------


def _all_sources() -> list[Path]:
    return sorted(SYNTHETIC.rglob("*.eml"))


def test_there_are_synthetic_sources() -> None:
    assert len(_all_sources()) >= 7, "tests/fixtures/synthetic/basics/ should hold seven messages"


@pytest.mark.parametrize("source", _all_sources(), ids=lambda p: str(p.relative_to(SYNTHETIC)))
def test_source_uses_only_reserved_domains_and_fixed_ids(source: Path) -> None:
    """No real person, company or mail may enter a synthetic fixture, and its
    output must be reproducible: every address is under a reserved domain
    (RFC 2606 / RFC 6761), and Date and Message-ID are authored, not left for
    a tool to invent."""
    msg = email.message_from_bytes(source.read_bytes(), policy=email.policy.default)
    for header in ("From", "To", "Cc", "Bcc"):
        for _, addr in _addresses(msg, header):
            assert addr.rsplit("@", 1)[1] in ALLOWED_DOMAINS, f"{source.name}: {header} {addr}"
    assert msg["From"] is not None and msg["Date"] is not None, source.name
    message_id = msg["Message-ID"]
    assert message_id is not None and message_id.endswith("@example.test>"), source.name


def test_basics_covers_the_six_cases() -> None:
    """The row's brief, as a test: plain, HTML, non-Latin subject, two
    attachments, To+Cc+Bcc, empty subject — and a second folder."""
    msgs = expected_messages()
    assert {m.folder for m in msgs} == {"Inbox", "Sent"}
    assert any(m.body_text and not m.body_html and not m.attachments for m in msgs), "plain"
    assert any(m.body_html for m in msgs), "HTML"
    assert any(not m.subject.isascii() and not m.sender_name.isascii() for m in msgs), "non-Latin"
    two = [m for m in msgs if len(m.attachments) == 2]
    assert two and {mime for _, mime, _ in two[0].attachments} == {"text/plain", "image/png"}
    assert any({t for t, _, _ in m.recipients} == {MAPI_TO, MAPI_CC, MAPI_BCC} for m in msgs), "To/Cc/Bcc"
    assert any(m.subject == "" for m in msgs), "empty subject"
    assert STORE.stat().st_size < 100 * 1024, "the generated store should stay small"


# --- 1. goldens ------------------------------------------------------------------


@pytest.mark.parametrize("example", ADMISSION_EXAMPLES)
def test_oracle_reads_the_store(golden_exit, example: str) -> None:
    """The admission rule of todo/T06 § P20-SYNTH, kept true: a synthetic
    store is first-class only while upstream reads it end to end."""
    assert golden_exit(STORE, example) == 0, f"upstream {example} refuses synth-basics.pst"


def test_oracle_refuses_search_updates_as_documented(golden_exit) -> None:
    """EMLtoPST writes no search-management queue (NID 0x1E1), so upstream's
    read_search_updates fails with "BTENTRY not found". The corpus README row
    says so; if this starts passing, that row is stale."""
    assert golden_exit(STORE, "read_search_updates") != 0


def test_store_props_show_the_recipe(golden) -> None:
    text = golden(STORE, "read_store_props")
    assert "Display Name: synth-basics\n" in text
    key = hashlib.sha256(b"pypst synthetic fixture: basics").digest()[:16]
    key_text = "-".join(f"{b:02X}" for b in key)
    entry_ids = dict(re.findall(r"^(IPM Subtree|Deleted Items|Finder): EntryId \{ record_key: ([0-9A-F-]+), node_id: NodeId \{ NormalFolder: 0x[0-9A-F]+ \} \}$", text, re.MULTILINE))
    assert set(entry_ids) == {"IPM Subtree", "Deleted Items", "Finder"}
    assert set(entry_ids.values()) == {key_text}, "record key is not the one make_fixture.py derives"
    nodes = re.findall(r"NormalFolder: (0x[0-9A-F]+)", text)
    assert len(set(nodes)) == 3, "the three special folders must be three folders"


def test_root_folder_holds_ipm_subtree_and_search_root(golden) -> None:
    table = folder_table(golden(STORE, "read_root_folder"))
    assert set(table) == {IPM_SUBTREE_NAME, FINDER_NAME}
    assert table[IPM_SUBTREE_NAME]["has_subfolders"] is True
    assert table[FINDER_NAME] == {"count": 0, "unread": 0, "has_subfolders": False}


def test_ipm_subtree_lists_the_authored_folders_with_their_counts(golden) -> None:
    """Folder names and per-folder message counts, from the sources."""
    table = folder_table(golden(STORE, "read_ipm_subtree"))
    want = expected_folder_counts() | {WASTEBASKET_NAME: 0}
    assert {name: row["count"] for name, row in table.items()} == want
    assert all(row["unread"] == 0 and row["has_subfolders"] is False for row in table.values())


# --- 2. bytes ------------------------------------------------------------------


@pytest.fixture(scope="module")
def store_bytes() -> bytes:
    data = STORE.read_bytes()
    assert data[:4] == b"!BDN"
    # Everything below depends on this: values are searchable only because
    # the tool writes bCryptMethod = NDB_CRYPT_NONE.
    assert data[CRYPT_METHOD_OFFSET] == NDB_CRYPT_NONE, "synth-basics.pst is encrypted; the byte tier is void"
    return data


def _ids(messages: list[ExpectedMessage]) -> list[str]:
    return [m.source.relative_to(SOURCES).as_posix() for m in messages]


@pytest.mark.parametrize("message", expected_messages(), ids=_ids(expected_messages()))
def test_subject_sender_and_recipients_are_stored(store_bytes: bytes, message: ExpectedMessage) -> None:
    if message.subject:
        assert message.subject.encode("utf-16-le") in store_bytes, f"subject of {message.source.name}"
    assert message.sender_name.encode("utf-16-le") in store_bytes, f"sender of {message.source.name}"
    assert message.sender_email.encode("utf-16-le") in store_bytes
    for _, name, addr in message.recipients:
        assert name.encode("utf-16-le") in store_bytes, f"recipient {name!r} of {message.source.name}"
        assert addr.encode("utf-16-le") in store_bytes, f"recipient {addr!r} of {message.source.name}"


@pytest.mark.parametrize("message", expected_messages(), ids=_ids(expected_messages()))
def test_bodies_are_stored(store_bytes: bytes, message: ExpectedMessage) -> None:
    if message.body_text is not None:
        assert _utf16_present(store_bytes, message.body_text), f"plain body of {message.source.name}"
    if message.body_html is not None:
        # PR_HTML is the HTML's bytes, not UTF-16.
        assert any(f.encode("utf-8") in store_bytes for f in _text_forms(message.body_html)), (
            f"HTML body of {message.source.name}"
        )


def test_attachments_are_stored_verbatim(store_bytes: bytes) -> None:
    (message,) = [m for m in expected_messages() if m.attachments]
    assert len(message.attachments) == 2
    for filename, mime, payload in message.attachments:
        assert filename.encode("utf-16-le") in store_bytes, filename
        assert mime.encode("utf-16-le") in store_bytes, mime
        assert payload in store_bytes, f"payload of {filename}"
    png = {name: payload for name, _, payload in message.attachments}["swatch.png"]
    assert png == make_swatch_png(), "the PNG is not the stdlib recipe's output"
    assert len(png) < 256 and png.startswith(b"\x89PNG\r\n\x1a\n")
    width, height = struct.unpack(">II", png[16:24])
    assert (width, height) == (8, 8)


def test_empty_subject_is_empty_not_a_placeholder(store_bytes: bytes) -> None:
    """The unpatched tool writes "(No Subject)" for a missing header; the
    patch in scripts/patches/ removes that so the reader meets an empty
    PT_UNICODE, which is the case the sixth message exists to exercise."""
    assert any(m.subject == "" for m in expected_messages())
    assert "(No Subject)".encode("utf-16-le") not in store_bytes


# --- 3. the reader (P07–P09) ---------------------------------------------------


@pytest.fixture(scope="module")
def reader():
    """`pypst` with its messaging surface, or skip. Written to
    docs/INTERFACES.md § messaging; nothing here should need editing when
    P07–P09 land, only un-skipping."""
    pypst = pytest.importorskip("pypst")
    missing = [name for name in ("Store", "Folder", "Message", "Attachment") if not hasattr(pypst, name)]
    if missing:
        pytest.skip(f"pypst messaging surface not landed yet: {missing}")
    return pypst


@pytest.fixture(scope="module")
def opened(reader):
    with reader.Store.open(STORE) as store:
        yield store


def _folders_by_name(store) -> dict[str, object]:
    return {folder.display_name: folder for folder in store.root_folder.walk()}


def test_reader_display_name_and_folders(opened) -> None:
    assert opened.display_name == "synth-basics"
    folders = _folders_by_name(opened)
    assert {IPM_SUBTREE_NAME, FINDER_NAME, WASTEBASKET_NAME, "Inbox", "Sent"} <= set(folders)
    for name, count in (expected_folder_counts() | {WASTEBASKET_NAME: 0}).items():
        assert folders[name].content_count == count, name
        assert len(list(folders[name].messages())) == count, name
    ipm = opened.open_folder(opened.ipm_subtree)
    assert ipm.display_name == IPM_SUBTREE_NAME
    assert {f.display_name for f in ipm.subfolders()} == set(expected_folder_counts()) | {WASTEBASKET_NAME}


def _read_messages(opened) -> dict[str, list[object]]:
    return {name: list(folder.messages()) for name, folder in _folders_by_name(opened).items()}


@pytest.mark.parametrize("expected", expected_messages(), ids=_ids(expected_messages()))
def test_reader_message_content(opened, expected: ExpectedMessage) -> None:
    """Subject, sender, bodies, recipients and attachments, read back."""
    candidates = [
        m
        for m in _read_messages(opened)[expected.folder]
        if m.subject == expected.subject and m.sender_name == expected.sender_name
    ]
    assert len(candidates) == 1, f"{expected.source.name}: {len(candidates)} messages match"
    message = candidates[0]
    assert message.message_class == "IPM.Note"
    assert message.sender_email == expected.sender_email

    if expected.body_text is None:
        assert message.body_text in (None, "")
    else:
        assert message.body_text in _text_forms(expected.body_text)
    if expected.body_html is None:
        assert message.body_html is None
    else:
        assert message.body_html.decode("utf-8") in _text_forms(expected.body_html)

    got = sorted((int(r.type), r.name, r.email) for r in message.recipients())
    assert got == sorted(expected.recipients)

    attachments = list(message.attachments())
    assert [(a.long_filename, a.mime_tag, a.data()) for a in attachments] == expected.attachments
    for attachment, (_, _, payload) in zip(attachments, expected.attachments):
        assert attachment.size == len(payload)
        assert attachment.embedded_message() is None


# --- 4. the committed store regenerates ----------------------------------------


def test_committed_store_regenerates_from_its_sources() -> None:
    """`scripts/make_fixture.py --check basics`: the pinned, patched tool over
    the committed sources produces exactly the committed bytes. Skips on a
    checkout without the tool (a fresh clone stays green); fails on a tool
    that is present but not at the pin — that is a real drift."""
    if not (TOOL / ".git").exists():
        pytest.skip("reference/EMLtoPST absent — run scripts/get_fixture_tools.sh")
    proc = subprocess.run(
        [sys.executable, str(MAKE_FIXTURE), "--check", "basics"],
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    assert proc.returncode == 0, f"exit {proc.returncode}\n{proc.stdout}\n{proc.stderr}"
