"""The [MS-OXRTFCP] initial dictionary — mechanically extracted, not transcribed.

Ported from: crates/compressed-rtf/src/dictionary.rs (`INITIAL_DICTIONARY`)
Upstream:    microsoft/outlook-pst-rs @ cfb721daee538acc50d2bad6faac5ce724f6037d
Spec:        [MS-OXRTFCP] 2.1.2.1 Dictionary

This file was GENERATED by scripts/extract_rtf_dictionary.py reading the
upstream Rust source directly. Do not hand-edit it: every LZFu-compressed
body refers back into these 207 bytes, so a single wrong byte here corrupts
one character of the RTF preamble of every message and looks like a parser
bug two layers up. Regenerate it instead. The script proves, on the way
through, that the bytes are exactly 207 long, equal the string the
specification prints, and carry the pinned CRC-32; tests/test_rtf.py re-proves
the same three facts against the committed module.
"""

from __future__ import annotations

# Decoded, it reads (with <CR><LF> at offsets 168-169):
#   {\rtf1\ansi\mac\deff0\deftab720{\fonttbl;}{\f0\fnil \froman \fswiss \fmodern
#   \fscript \fdecor MS Sans SerifSymbolArialTimes New RomanCourier{\colortbl
#   \red0\green0\blue0<CR><LF>\par \pard\plain\f0\fs20\b\i\u\tab\tx
INITIAL_DICTIONARY: bytes = bytes(
    [
        123, 92, 114, 116, 102, 49, 92, 97, 110, 115, 105, 92,
        109, 97, 99, 92, 100, 101, 102, 102, 48, 92, 100, 101,
        102, 116, 97, 98, 55, 50, 48, 123, 92, 102, 111, 110,
        116, 116, 98, 108, 59, 125, 123, 92, 102, 48, 92, 102,
        110, 105, 108, 32, 92, 102, 114, 111, 109, 97, 110, 32,
        92, 102, 115, 119, 105, 115, 115, 32, 92, 102, 109, 111,
        100, 101, 114, 110, 32, 92, 102, 115, 99, 114, 105, 112,
        116, 32, 92, 102, 100, 101, 99, 111, 114, 32, 77, 83,
        32, 83, 97, 110, 115, 32, 83, 101, 114, 105, 102, 83,
        121, 109, 98, 111, 108, 65, 114, 105, 97, 108, 84, 105,
        109, 101, 115, 32, 78, 101, 119, 32, 82, 111, 109, 97,
        110, 67, 111, 117, 114, 105, 101, 114, 123, 92, 99, 111,
        108, 111, 114, 116, 98, 108, 92, 114, 101, 100, 48, 92,
        103, 114, 101, 101, 110, 48, 92, 98, 108, 117, 101, 48,
        13, 10, 92, 112, 97, 114, 32, 92, 112, 97, 114, 100,
        92, 112, 108, 97, 105, 110, 92, 102, 48, 92, 102, 115,
        50, 48, 92, 98, 92, 105, 92, 117, 92, 116, 97, 98,
        92, 116, 120,
    ]
)

"""207 bytes: the ASCII string every LZFu dictionary starts life holding."""
