#!/usr/bin/env python3
"""Regenerate src/pypstreader/_tables.py from the upstream Rust source.

The 768-byte MS-PST key table is the one piece of this port where a
transcription slip would be both silent and devastating: a wrong byte
corrupts one byte in 256 of every encoded block, and the damage surfaces
three layers up looking like a B-tree bug. So it is never typed. It is
read out of `crates/pst/src/encode/mod.rs` and written here, and three
invariants are proven on the way through.

Usage:  python3 scripts/extract_key_data.py [--check]

    --check   verify the committed _tables.py matches the upstream source
              and exit non-zero if it does not (this is what CI runs)
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
UPSTREAM = REPO / "reference" / "outlook-pst-rs" / "crates" / "pst" / "src" / "encode" / "mod.rs"
TARGET = REPO / "src" / "pypstreader" / "_tables.py"


def _pin() -> str:
    """The upstream revision this checkout is parked on, for the header."""
    try:
        out = subprocess.run(
            ["git", "-C", str(UPSTREAM.parents[4]), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip()
    except (subprocess.CalledProcessError, OSError, IndexError):
        return "unknown"


def extract() -> list[int]:
    if not UPSTREAM.exists():
        sys.exit(
            f"upstream source not found at {UPSTREAM}\n"
            "run scripts/get_rust_source.sh first"
        )
    body = re.search(
        r"static KEY_DATA: \[u8; 768\] = \[(.*?)\];", UPSTREAM.read_text(), re.DOTALL
    )
    if body is None:
        sys.exit(
            "KEY_DATA not found in the upstream file — upstream may have "
            "restructured encode/mod.rs; read it before touching this script"
        )
    vals = [int(x) for x in re.findall(r"\d+", body.group(1))]

    # Three invariants, checked here rather than trusted. Each of the three
    # 256-byte tables must be a permutation of 0..255, and I must invert R —
    # that last one is the property that makes permutative DECODING work at
    # all, so if it fails, nothing downstream is worth debugging.
    if len(vals) != 768:
        sys.exit(f"expected 768 bytes, extracted {len(vals)}")
    for name, chunk in (("R", vals[:256]), ("S", vals[256:512]), ("I", vals[512:])):
        if sorted(chunk) != list(range(256)):
            sys.exit(f"table {name} is not a permutation of 0..255")
    R, I = vals[:256], vals[512:]
    if any(I[R[b]] != b for b in range(256)):
        sys.exit("table I is not the inverse of table R")
    return vals


def render(vals: list[int]) -> str:
    rows = "\n".join(
        "        " + " ".join(f"{v}," for v in vals[i : i + 12]) for i in range(0, 768, 12)
    )
    return f'''"""The MS-PST permutation tables — mechanically extracted, not transcribed.

Ported from: crates/pst/src/encode/mod.rs (`static KEY_DATA: [u8; 768]`)
Upstream:    microsoft/outlook-pst-rs @ {_pin()}
Spec:        [MS-PST] 5.1 Permutative Encoding / 5.2 Cyclic Encoding

This file was GENERATED by scripts/extract_key_data.py reading the upstream
Rust source directly. Do not hand-edit it: a single mistyped byte here
corrupts one byte in every 256 of every encoded block, which is exactly the
kind of damage that looks like a parser bug three layers up. Regenerate it
instead, and let tests/test_tables.py re-prove the three invariants:
R, S and I are each permutations of 0..255, and I is the inverse of R.
"""

from __future__ import annotations

KEY_DATA: bytes = bytes(
    [
{rows}
    ]
)

"""768 bytes: three 256-byte substitution tables laid end to end."""

KEY_DATA_R: bytes = KEY_DATA[:256]
KEY_DATA_S: bytes = KEY_DATA[256:512]
KEY_DATA_I: bytes = KEY_DATA[512:]
'''


def main() -> int:
    vals = extract()
    rendered = render(vals)
    if "--check" in sys.argv:
        current = TARGET.read_text() if TARGET.exists() else ""
        # Compare the DATA, not the header: the header carries the upstream
        # revision, which legitimately moves when the pin moves.
        def data_only(text: str) -> str:
            return "".join(re.findall(r"^\s+\d+,.*$", text, re.MULTILINE))

        if data_only(current) != data_only(rendered):
            print("_tables.py does not match the upstream source — regenerate it")
            return 1
        print("_tables.py matches upstream")
        return 0
    TARGET.write_text(rendered)
    print(f"wrote {TARGET.relative_to(REPO)} (768 bytes, 3 invariants proven)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
